### ISSUE TITLE
[Request] The ability to add variation to time passcode

### ISSUE THREAD

**Issue by ymarcus93** [hetelek/TimePasscode#2]
I was thinking that there could be in the preferences an option to add variation to the time passcode. For example, the user can say +1 to the hour and +20 to the minutes. This allows some variation for the passcode and an even more secure atmosphere.

**Comment by hetelek** [comment]
Yes, many people have been requesting this, and you can expect it to be implemented in the near future. Thanks for the request!

**Comment by ymarcus93** [comment]
I am trying to add this feature to the tweak, but I keep getting this error on xcode when I click run.
![error](https://f.cloud.github.com/assets/1643346/2061271/fc91c474-8c49-11e3-819c-3a6b6126f578.jpg)

Do you know how I can help develop for this tweak?

**Comment by hetelek** [comment]
Tweaks are (generally) not developed in Xcode. Most developers use something called [Theos](http://iphonedevwiki.net/index.php/Theos/Getting_Started) to help them out. To contribute to TimePasscode, you must use Theos.
